### ISSUE TITLE
hostname node value in config and service name

### ISSUE THREAD

**Issue by emremogn** [GoogleCloudPlatform/endpoints-framework-maven-plugin#29]
I've noticed that the text value of the hostname node in plugin config is used to generate the endpoints service name (using command` mvn endpoints-framework:openApiDocs`); so the service name is not `api-name.endpoints.project-id.cloud.goog`, but `project-id.appspot.com`.

Everything works fine and the only caveat is to use the same service name for ENDPOINTS_SERVICE_NAME variable in appengine-web.xml and for endpoints.serviceName param in web.xml.

But is the service name `project-id.**appspot.com**` ok? This page https://cloud.google.com/endpoints/docs/frameworks/naming-your-api-service suggests other naming strategies.
Is the globally unique name `project-id.**appspot.com**` an allowed name for service name?

Thank you.

**Comment by loosebazooka** [comment]
@tangiel

**Comment by tangiel** [comment]
Yes, it is. We are actually in the process of changing the docs back to using appspot.com for App Engine Standard.
