### ISSUE TITLE
Allow running tasks without forking.

### ISSUE THREAD

**Issue by sylvain1811** [GoogleCloudPlatform/endpoints-framework-maven-plugin#51]
I'm using the plugin in my `pom.xml` and it works but many tasks are executed twice. I think that the plugin fork the lifecycle, but I found no way to disable forking.

I've posted a question [here](https://stackoverflow.com/questions/47894818/why-does-maven-execute-some-tasks-twice). There is my `pom.xml` if you want to check it.

Maybe I'm using the plugin wrong, maybe it's an issue, let me know!

**Comment by patflynn** [comment]
assigning to @loosebazooka for triage.

**Comment by loosebazooka** [comment]
The plugin is forking the lifecycle so that the user doesn't have to configure the lifecycle execution. But it appears that doesn't cover all the cases. We should probably include a way to run non-forked if you're configuring the task yourself.

**Comment by sylvain1811** [comment]
Did you plan a release of these changes ?
