### ISSUE TITLE
Expose info.version as a param that can be passed in through the POM

### ISSUE THREAD

**Issue by quentin-sensome** [GoogleCloudPlatform/endpoints-framework-maven-plugin#57]
Hi,

It would be nice to be able to configure the version of the OpenAPI specifications via the `pom.xml` file. Something like this:

```
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>endpoints-framework-maven-plugin</artifactId>
  <version>2.0.0</version>
  <configuration>
    <basePath>/_ah/api</basePath>
    <hostname>myapp.appspot.com</hostname>
    <info.version>1.0.0</info.version>
  </configuration>
</plugin>
```

As of now, it makes it quite difficult to use the plugin with configuration management tools, and forces to intervene manually in deployment pipelines to increment versions. Having the possibility to configure this would smoothen the process a lot.

**Comment by patflynn** [comment]
So this would have to be a FR against the tool first?

**Comment by tangiel** [comment]
Yep.

**Comment by patflynn** [comment]
@quentin-sensome you may want to follow https://github.com/cloudendpoints/endpoints-java/issues/156 to see if this gets prioritized.

**Comment by JoeWang1127** [comment]
close as not planned
